apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: name-mutator-webhook-cfg
  labels:
    app: name-mutator
webhooks:
- name: name-mutator.codius.org
  clientConfig:
    service:
      name: name-mutator-webhook-svc
      namespace: name-mutator
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
    scope: "Namespaced"
  namespaceSelector:
    matchLabels:
      name-mutation: enabled
