apiVersion: v1
kind: Service
metadata:
  name: name-mutator-webhook-svc
  namespace: name-mutator
  labels:
    app: name-mutator
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: name-mutator
